version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ozon
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  url-shortener:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - STORAGE=in-memory #или in-memory \ postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=ozon
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  postgres_data:
