version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ozon
    ports:
      - 5432:5432
  url-shortener:
    build:
      context: ./cmd/ozon
      dockerfile: ../../Dockerfile
    environment:
      - STORAGE=postgres # or 'in-memory' based on your needs
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=ozon
    ports:
      - 8000:8000
    depends_on:
      - postgres
